# Generated by Django 5.0.7 on 2024-07-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
